name: 🚀 Deploy

on:
  push:
    branches:
      - main
#      - sandbox
#      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: Run Laravel Tests
        uses: ./.github/actions/laravel-tests

      - name: 🔐 Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      # =========================
      # 🚀 PRODUÇÃO
      # =========================
      - name: 🚀 Deploy Production
        if: github.ref == 'refs/heads/main'
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} \
          "cd /var/www/bhcosta90 && ./deploy.sh release main"

      # =========================
      # 🔬 SANDBOX
      # =========================
      - name: 🔬 Deploy Sandbox
        if: github.ref == 'refs/heads/sandbox'
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} \
          "cd /var/www/bhcosta90 && ./deploy.sh release sandbox"

      # =========================
      # 🧪 DEVELOP
      # =========================
      - name: 🧪 Deploy Develop
        if: github.ref == 'refs/heads/develop'
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} \
          "cd /var/www/bhcosta90 && ./deploy.sh unique develop"