name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.4'
      - uses: actions/checkout@v4
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite
      - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: composer ci
      #    - name: Deploy on Forge
      #      uses: jbrooksuk/laravel-forge-action@v1.0.2
      #      with:
      #        trigger_url: ${{ secrets.TRIGGER_URL }}

      - name: Instalar o PHP e dependências
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, bcmath, openssl, pdo, tokenizer, xml, ctype, json, curl
          tools: composer, envoy

      - name: Criar .env temporário para o Envoy
        run: |
          echo "DEPLOY_SERVERS_WEB=${{ secrets.DEPLOY_SERVERS_WEB }}" > .env

      - name: Configurar chave SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # Extrai o host do DEPLOY_SERVER (remove user@)
          DEPLOY_HOST=$(echo "${{ secrets.DEPLOY_SERVERS_WEB }}" | cut -d'@' -f2)

          # Adiciona fingerprint ao known_hosts
          ssh-keyscan -H "$DEPLOY_HOST" >> ~/.ssh/known_hosts

      - name: Executar Laravel Envoy
        run: vendor/bin/envoy run deploy

